"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import { useEffect, useState ,createContext} from 'react';

const inter = Inter({ subsets: ['latin'] })
export const ProductsContext = createContext()

export const metadata = {
  title: 'Create Next App olgu',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [state,setState]=useState(false)
  const handleState=()=> {
    setState(true)
  }
  const [user,setuser] = useState('')
  const handlesetuser = (a:string) => {
        setuser(a)
  }
  const [data, setData] = useState();
  useEffect(() => {
    // fetch data
    const dataFetch = async () => {
      const data = await (
        await fetch(
          "https://dummyjson.com/users"
        )
      ).json();

      // set state when the data received
      setData(data);
    };

    dataFetch();
  }, []);
  console.log(data)
  return (
    <html lang="en">
      <body className={inter.className}>
      <ProductsContext.Provider value={{state:state,handleState,handlesetuser,user}}>
      {children}
  </ProductsContext.Provider>
        
      </body>
    </html>
  )
}
