"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import { useEffect, useState ,createContext} from 'react';

const inter = Inter({ subsets: ['latin'] })
export const ProductsContext = createContext(null)

export const metadata = {
  title: 'Create Next App olgu',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [state,setState]=useState(false)
  const handleState=()=> {
    setState(true)
  }
  const [user,setuser] = useState('')
  const handlesetuser = (a:string) => {
        setuser(a)
  }
  const [data, setData] = useState<[]>();
  useEffect(() => {
    // fetch data
    const dataFetch = async () => {
      const data = await (
        await fetch(
          "https://dummyjson.com/users"
        )
      ).json();

      // set state when the data received
      setData(data.users);
    };

    dataFetch();
  }, []);
  type user = {
    firstName: string,
    email:string,
    university:string,
    id:number,
    domain:string,
    phone:string,
    image:string
  }
  const adduser = (user:user) => {
    setData([...data,user])
  }
  const edituser = (id,user) => {
    setData(a=> a.map(k=>k.id==id ? {...k,...user} : {...k}))
  }
  const removeuser =(id) => {
        setData(a=>a.filter(k=>k.id !=id))
  }
  // const searchuser = (value) => {
  //   setData(k=>k.filter(function(a,b){
     
  //     return a.firstName.toLowerCase().indexOf(value.toLowerCase()) !== -1 
  //     || a.email.toLowerCase().indexOf(value.toLowerCase()) !== -1
  //     || a.university.toLowerCase().indexOf(value.toLowerCase()) !== -1;
  //   }))
  // }
 // console.log(data)
  return (
    <html lang="en">
      <body className={inter.className}>
      <ProductsContext.Provider value={{state:state,handleState,handlesetuser,user,data,adduser,edituser,removeuser}}>
      {children}
  </ProductsContext.Provider>
        
      </body>
    </html>
  )
}
